# Site settings
title: binarin.ru
email: binarin@binarin.ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://binarin.ru" # the base hostname & protocol for your site
twitter_username: binarin
github_username:  binarin
copyright_name: Alexey Lebedeff

# Build settings
markdown: kramdown
paginate: 5
permalink: pretty
gems:
  - jekyll-paginate

navigation:
- text: binarin.ru
  url: /
- text: About
  url: /about/
